import { BLOB_VERTEX_DEFAULT_RADII } from "../geometry/metrics.js";

export { BLOB_VERTEX_DEFAULT_RADII };

export const EDGE_DEFINITIONS = new Map([
  ["plain", { type: "plain" }],
  ["line", { type: "plain" }],
  ["propagator", { type: "plain" }],
  ["fermion", { type: "fermion", arrow: "forward" }],
  ["anti fermion", { type: "fermion", arrow: "reverse" }],
  ["anti-fermion", { type: "fermion", arrow: "reverse" }],
  ["antifermion", { type: "fermion", arrow: "reverse" }],
  ["photon", { type: "photon" }],
  ["boson", { type: "photon" }],
  ["charged boson", { type: "photon", arrow: "forward" }],
  ["charged-boson", { type: "photon", arrow: "forward" }],
  ["anti charged boson", { type: "photon", arrow: "reverse" }],
  ["anti-charged-boson", { type: "photon", arrow: "reverse" }],
  ["gluon", { type: "gluon" }],
  ["scalar", { type: "scalar" }],
  ["charged scalar", { type: "scalar", arrow: "forward" }],
  ["charged-scalar", { type: "scalar", arrow: "forward" }],
  ["anti charged scalar", { type: "scalar", arrow: "reverse" }],
  ["anti-charged-scalar", { type: "scalar", arrow: "reverse" }],
  ["ghost", { type: "ghost" }],
  ["dashed", { type: "dashed" }],
  ["dot dashed", { type: "dashdot" }],
  ["dot-dashed", { type: "dashdot" }],
  ["dashdot", { type: "dashdot" }],
  ["dash-dot", { type: "dashdot" }],
  ["triangle", { type: "triangle" }],
  ["zigzag", { type: "triangle" }],
  ["square", { type: "square" }],
  ["rectangle", { type: "square" }],
  ["rectangular", { type: "square" }],
  ["double", { type: "double" }],
  ["eikonal", { type: "double", arrow: "forward" }],
  ["wilson line", { type: "double", arrow: "forward" }],
  ["wilson-line", { type: "double", arrow: "forward" }],
  ["invisible", { type: "invisible", hidden: true }],
  ["hidden", { type: "invisible", hidden: true }],
]);

export const SIZE_PRESETS = {
  small: { width: 420, minHeight: 280, marginX: 70, marginY: 46, externalGap: 82 },
  medium: { width: 520, minHeight: 330, marginX: 82, marginY: 52, externalGap: 100 },
  large: { width: 760, minHeight: 480, marginX: 110, marginY: 70, externalGap: 140 },
};

export const DEFAULT_DIAGRAM_OPTIONS = {
  layout: "spring",
  orientation: "horizontal",
  size: "medium",
};

export const VERTEX_SHAPES = new Map([
  ["dot", "dot"],
  ["square dot", "square-dot"],
  ["square-dot", "square-dot"],
  ["square", "square-dot"],
  ["empty dot", "empty-dot"],
  ["empty-dot", "empty-dot"],
  ["crossed dot", "crossed-dot"],
  ["crossed-dot", "crossed-dot"],
  ["cross dot", "crossed-dot"],
  ["cross-dot", "crossed-dot"],
  ["cross", "cross"],
  ["blob", "blob"],
  ["disk", "disk"],
  ["large blob", "disk"],
  ["large-blob", "disk"],
]);

export const BLOB_VERTEX_SIZE_PRESETS = new Map([
  ["tiny", 8],
  ["small", 14],
  ["medium", BLOB_VERTEX_DEFAULT_RADII.blob],
  ["large", 28],
  ["huge", BLOB_VERTEX_DEFAULT_RADII.disk],
  ["disk", BLOB_VERTEX_DEFAULT_RADII.disk],
]);

export const BLOB_HATCHES = new Map([
  ["hatched", "diagonal"],
  ["hatch", "diagonal"],
  ["diagonal", "diagonal"],
  ["diagonal right", "diagonal"],
  ["forward diagonal", "diagonal"],
  ["slash", "diagonal"],
  ["north east", "diagonal"],
  ["north east lines", "diagonal"],
  ["ne", "diagonal"],
  ["diagonal reverse", "diagonal-reverse"],
  ["diagonal left", "diagonal-reverse"],
  ["reverse diagonal", "diagonal-reverse"],
  ["backward diagonal", "diagonal-reverse"],
  ["backslash", "diagonal-reverse"],
  ["north west", "diagonal-reverse"],
  ["north west lines", "diagonal-reverse"],
  ["nw", "diagonal-reverse"],
  ["cross", "cross"],
  ["cross hatch", "cross"],
  ["crosshatch", "cross"],
  ["cross hatched", "cross"],
  ["horizontal", "horizontal"],
  ["horizontal lines", "horizontal"],
  ["vertical", "vertical"],
  ["vertical lines", "vertical"],
  ["grid", "grid"],
  ["grid lines", "grid"],
]);
